# Copyright (c) 2022 SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatekeeper-policy-manager
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind": "OAuthRedirectReference", "apiVersion": "v1", "reference": {"kind": "Route", "name": "policy-manager"}}'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatekeeper-policy-manager-crd-view
rules:
- apiGroups: ["constraints.gatekeeper.sh"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["templates.gatekeeper.sh"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["config.gatekeeper.sh"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatekeeper-policy-manager-crd-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatekeeper-policy-manager-crd-view
subjects:
- kind: ServiceAccount
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
- kind: ServiceAccount
  name: gatekeeper-policy-manager
  namespace: openshift-gatekeeper-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatekeeper-policy-manager-oauth-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: gatekeeper-policy-manager
  namespace: gatekeeper-system
- kind: ServiceAccount
  name: gatekeeper-policy-manager
  namespace: openshift-gatekeeper-system

---

# bind to this role to allow user access to grafana UI
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gatekeeper-policy-manager-access
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
